#!/usr/bin/env python
#Copyright 2007,2008 Sebastian Hagen
# This file is part of liasis.
#
# liasis is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# liasis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from liasis.benc_structures import BTMetaInfo

if (__name__ == '__main__'):
   import sys
   tf_name = sys.argv[1]
   tf = open(tf_name,'rb')
   mi = BTMetaInfo.build_from_benc_stream(tf)

   print('\n'.join(mi.hr_format_lines()))

